version: '3.7'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports: 
      - 6379:6379

  # rentalx:
  #   links:
  #     - database
  #   depends_on:
  #     - database
  #   build: .
  #   container_name: rentalx
  #   ports: 
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app

volumes:
  pgdata:
    driver: local